// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package user_db

import (
	"context"
)

const getUserAndPass = `-- name: GetUserAndPass :one
SELECT password FROM Users WHERE username = ?
`

func (q *Queries) GetUserAndPass(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserAndPass, username)
	var password string
	err := row.Scan(&password)
	return password, err
}
