// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package material_db

import (
	"database/sql"
	"time"
)

type CheckoutLog struct {
	ID           int64
	ItemID       int64
	UserID       int64
	CheckinTime  time.Time
	CheckoutTime time.Time
}

type JobSite struct {
	ID          int64
	Name        string
	Addr        sql.NullString
	LocationLat sql.NullFloat64
	LocationLng sql.NullFloat64
}

type Material struct {
	ID             int64
	Name           sql.NullString
	Type           sql.NullString
	Quantity       int64
	Unit           string
	Status         string
	LocationLat    sql.NullFloat64
	LocationLng    sql.NullFloat64
	LastCheckedOut interface{}
	JobSite        sql.NullInt64
}

type MaterialLog struct {
	ID             int64
	MaterialID     int64
	Note           sql.NullString
	Status         string
	QuantityChange int64
	Timestamp      time.Time
}

type User struct {
	ID       int64
	SiteID   sql.NullInt64
	Username string
	Password string
	Role     string
}
