// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package user_db

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO Users(username, password, name, company, site, role) VALUES (?,?,?,?,?,?) RETURNING id, username, password, name, company, site, role
`

type AddUserParams struct {
	Username string
	Password string
	Name     string
	Company  string
	Site     string
	Role     string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.Username,
		arg.Password,
		arg.Name,
		arg.Company,
		arg.Site,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.Company,
		&i.Site,
		&i.Role,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM Users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, name, company, site, role FROM Users
`

type GetAllUsersRow struct {
	ID       int64
	Username string
	Name     string
	Company  string
	Site     string
	Role     string
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Company,
			&i.Site,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, name, company, site, role FROM Users WHERE id = ?
`

type GetUserRow struct {
	ID       int64
	Username string
	Name     string
	Company  string
	Site     string
	Role     string
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Company,
		&i.Site,
		&i.Role,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE Users SET username = ?, password = ?, name = ?, company = ?, site = ?, role = ? WHERE id = ? RETURNING id, username, password, name, company, site, role
`

type UpdateUserParams struct {
	Username string
	Password string
	Name     string
	Company  string
	Site     string
	Role     string
	ID       int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.Password,
		arg.Name,
		arg.Company,
		arg.Site,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.Company,
		&i.Site,
		&i.Role,
	)
	return i, err
}
