// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package userdb

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :one
INSERT INTO Users(username, password, firstname, lastname, company, site, role, email, phone) VALUES (?,?,?,?,?,?,?,?,?) RETURNING id, username, password, firstname, lastname, company, site, role, email, phone
`

type AddUserParams struct {
	Username  string
	Password  string
	Firstname sql.NullString
	Lastname  sql.NullString
	Company   sql.NullString
	Site      sql.NullString
	Role      sql.NullString
	Email     string
	Phone     string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.Username,
		arg.Password,
		arg.Firstname,
		arg.Lastname,
		arg.Company,
		arg.Site,
		arg.Role,
		arg.Email,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.Company,
		&i.Site,
		&i.Role,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM Users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, password, firstname, lastname, company, site, role, email, phone FROM Users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Firstname,
			&i.Lastname,
			&i.Company,
			&i.Site,
			&i.Role,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, password, firstname, lastname, company, site, role, email, phone FROM Users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.Company,
		&i.Site,
		&i.Role,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const signUp = `-- name: SignUp :one
INSERT INTO Users(username, password, email, phone) VALUES (?,?,?,?) RETURNING id, username, password, firstname, lastname, company, site, role, email, phone
`

type SignUpParams struct {
	Username string
	Password string
	Email    string
	Phone    string
}

func (q *Queries) SignUp(ctx context.Context, arg SignUpParams) (User, error) {
	row := q.db.QueryRowContext(ctx, signUp,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.Company,
		&i.Site,
		&i.Role,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE Users SET username = ?, password = ?, firstname = ?, lastname = ?, company = ?, site = ?, role = ?, email = ?, phone = ? WHERE id = ? RETURNING id, username, password, firstname, lastname, company, site, role, email, phone
`

type UpdateUserParams struct {
	Username  string
	Password  string
	Firstname sql.NullString
	Lastname  sql.NullString
	Company   sql.NullString
	Site      sql.NullString
	Role      sql.NullString
	Email     string
	Phone     string
	ID        int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.Password,
		arg.Firstname,
		arg.Lastname,
		arg.Company,
		arg.Site,
		arg.Role,
		arg.Email,
		arg.Phone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.Company,
		&i.Site,
		&i.Role,
		&i.Email,
		&i.Phone,
	)
	return i, err
}
