// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: checkout.sql

package materialdb

import (
	"context"
)

const addCheckoutLog = `-- name: AddCheckoutLog :one
INSERT INTO CheckoutLogs(item_id,user_id,checkout_time)
VALUES (?,?,date())
RETURNING id, item_id, user_id, checkin_time, checkout_time
`

type AddCheckoutLogParams struct {
	ItemID int64 `json:"item_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddCheckoutLog(ctx context.Context, arg AddCheckoutLogParams) (CheckoutLog, error) {
	row := q.db.QueryRowContext(ctx, addCheckoutLog, arg.ItemID, arg.UserID)
	var i CheckoutLog
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UserID,
		&i.CheckinTime,
		&i.CheckoutTime,
	)
	return i, err
}

const getAllCheckoutLogs = `-- name: GetAllCheckoutLogs :one
SELECT id, item_id, user_id, checkin_time, checkout_time 
FROM  CheckoutLogs
`

func (q *Queries) GetAllCheckoutLogs(ctx context.Context) (CheckoutLog, error) {
	row := q.db.QueryRowContext(ctx, getAllCheckoutLogs)
	var i CheckoutLog
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UserID,
		&i.CheckinTime,
		&i.CheckoutTime,
	)
	return i, err
}

const updateCheckinlog = `-- name: UpdateCheckinlog :one
UPDATE CheckoutLogs
SET checkin_time = date()
WHERE id = ?
RETURNING id, item_id, user_id, checkin_time, checkout_time
`

func (q *Queries) UpdateCheckinlog(ctx context.Context, id int64) (CheckoutLog, error) {
	row := q.db.QueryRowContext(ctx, updateCheckinlog, id)
	var i CheckoutLog
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UserID,
		&i.CheckinTime,
		&i.CheckoutTime,
	)
	return i, err
}
