// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package materialdb

import (
	"database/sql"
	"time"
)

type CheckoutLog struct {
	ID           int64        `json:"id"`
	ItemID       int64        `json:"item_id"`
	UserID       int64        `json:"user_id"`
	CheckinTime  sql.NullTime `json:"checkin_time"`
	CheckoutTime time.Time    `json:"checkout_time"`
	Amount       interface{}  `json:"amount"`
}

type Material struct {
	ID             int64           `json:"id"`
	Name           sql.NullString  `json:"name"`
	Type           sql.NullString  `json:"type"`
	Quantity       int64           `json:"quantity"`
	Unit           string          `json:"unit"`
	Status         string          `json:"status"`
	LocationLat    sql.NullFloat64 `json:"location_lat"`
	LocationLng    sql.NullFloat64 `json:"location_lng"`
	LastCheckedOut sql.NullTime    `json:"last_checked_out"`
	JobSite        int64           `json:"job_site"`
}

type MaterialLog struct {
	ID             int64          `json:"id"`
	MaterialID     int64          `json:"material_id"`
	Note           sql.NullString `json:"note"`
	Status         string         `json:"status"`
	QuantityChange int64          `json:"quantity_change"`
	Timestamp      time.Time      `json:"timestamp"`
}
