// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package userdb

import (
	"context"
	"database/sql"
)

const getUserAndPass = `-- name: GetUserAndPass :one
SELECT username, password, id, role FROM Users WHERE username = ?
`

type GetUserAndPassRow struct {
	Username string         `json:"username"`
	Password string         `json:"password"`
	ID       int64          `json:"id"`
	Role     sql.NullString `json:"role"`
}

func (q *Queries) GetUserAndPass(ctx context.Context, username string) (GetUserAndPassRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAndPass, username)
	var i GetUserAndPassRow
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.ID,
		&i.Role,
	)
	return i, err
}
