// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package userdb

import (
	"context"
)

const getUserAndPass = `-- name: GetUserAndPass :one
SELECT password, id FROM Users WHERE username = ?
`

type GetUserAndPassRow struct {
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

func (q *Queries) GetUserAndPass(ctx context.Context, username string) (GetUserAndPassRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAndPass, username)
	var i GetUserAndPassRow
	err := row.Scan(&i.Password, &i.ID)
	return i, err
}
