// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package userdb

import (
	"database/sql"
)

type User struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Password  string         `json:"password"`
	Firstname sql.NullString `json:"firstname"`
	Lastname  sql.NullString `json:"lastname"`
	Company   sql.NullString `json:"company"`
	Site      sql.NullString `json:"site"`
	Role      sql.NullString `json:"role"`
	Email     string         `json:"email"`
	Phone     string         `json:"phone"`
}
