// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package userdb

import (
	"database/sql"
)

type User struct {
	ID        int64
	Username  string
	Password  string
	Firstname sql.NullString
	Lastname  sql.NullString
	Company   sql.NullString
	Site      sql.NullString
	Role      sql.NullString
	Email     string
	Phone     string
}
