version: "2"
sql:
  - engine: sqlite
    queries: ./queries/
    schema: ./migrations/
    gen:
      go:
        emit_json_tags: true
        package: <pkg-name>
        out: ../pkg/database/<sub-dir>/
