// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package material_db

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :one
INSERT INTO Users(username, site_id, role) VALUES (?,?,?) RETURNING id, site_id, username, password, role
`

type AddUserParams struct {
	Username string
	SiteID   sql.NullInt64
	Role     string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser, arg.Username, arg.SiteID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Username,
		&i.Password,
		&i.Role,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, site_id, role FROM Users
`

type GetAllUsersRow struct {
	ID       int64
	Username string
	SiteID   sql.NullInt64
	Role     string
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.SiteID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, site_id, role FROM Users WHERE id = ?
`

type GetUserRow struct {
	ID       int64
	Username string
	SiteID   sql.NullInt64
	Role     string
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SiteID,
		&i.Role,
	)
	return i, err
}
